
pipeline{
    agent any
    tools{
       jdk "Openjdk17"
       maven "MAVEN3"
    }
    stages{
        stage("Fetch source code"){
            steps{
                echo "========executing A========"
                git branch: 'main' , url:'https://github.com/geofLegrand/vprofile-project.git'
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
    }

}