
pipeline{
    agent any
    tools{
       jdk "Openjdk17"
       maven "MAVEN3"
    }
    stages{
        // stage("Fetch source code"){
        //     steps{
        //         echo "========executing A========"
        //         git branch: 'main' , url:'https://github.com/geofLegrand/vprofile-project.git'
        //     }

        // }
        stage("Build"){
            steps{
               sh 'mvn clean install'
            }
            
        }
        stage("Test the code"){
            steps{
                sh 'mvn test'
            }
        }
    }

}